In [39]:
import pandas as pd
import numpy as np

In [40]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')
df.head(100)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
95,1997,Asia,Gasoline,Front-wheel drive,3,2450,6,280.0,4540,18.7,28.6
96,1982,Europe,Gasoline,All-wheel drive,2,2370,6,237.0,4560,19.8,28.8
97,2003,USA,Gasoline,All-wheel drive,3,2140,5,229.0,4190,17.0,26.5
98,2018,Asia,Gasoline,Front-wheel drive,3,2290,6,250.0,4140,19.4,31.1
99,1976,Europe,Gasoline,Front-wheel drive,3,2290,6,NaN,4230,18.4,26.6

In [41]:
pd.__version__

'3.0.6'

In [42]:
len(df)

10000

In [43]:
df.shape

(10000, 11)

In [44]:
df['fuel_type'].nunique()

3

In [45]:
df.isnull().any().sum()

np.int64(2)

In [46]:
df['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [47]:
df['horsepower'].median()

np.float64(254.0)

In [48]:
# Example: filling missing values with 0
df_filled = df.fillna(0) 
new_median = df_filled['horsepower'].median()
print("New median:", new_median)

New median: 252.0

In [49]:
df_filled['vehicle_weight'].sum()

np.int64(42867540)

In [50]:
df_filtered = df_filled[df_filled['origin'] == 'Asia'] [['vehicle_weight', 'model_year']]
df_filtered

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

In [51]:
df_filtered = df_filled[df_filled['origin'] == 'Asia'][['vehicle_weight', 'model_year']]
df_filtered

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

In [52]:
df_filtered = df_filled.loc[df_filled['origin'] == 'Asia', ['vehicle_weight', 'model_year']]
df_filtered

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

In [70]:
df_filtered = df_filtered.head(7)

In [71]:
X = df_filtered.to_numpy()
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [72]:
XTX = X.T @ (X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [73]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [74]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [77]:
w = XTX_inv.dot(X.T).dot(y)
w

array([0.13644777, 0.2327492 ])

In [78]:
print (w.sum())

0.36919696904925486